[package]
name = "rupple"
version = "0.1.10"
edition = "2021"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = [
    "windows",
] }
ctrlc = "3.4.7"
rand = "0.9.1"
