#![allow(warnings)]
// autogenerated rupple file
use std::fmt::Debug;

/// Struct that can attempt to print an inner value with debug
/// If the inner value doesn't implement debug, nothing is printed instead
struct FalliblePrinter<T>(T);

impl<T: Debug> FalliblePrinter<T> {
    fn print(&self) {
        println!("\x1B[34m{:?}", self.0)
    }
}
trait NoDebug {
    fn print(&self);
}
impl<T> NoDebug for FalliblePrinter<T> {
    fn print(&self) {}
}

fn main() {
    let output = {
        // user input
    };
    FalliblePrinter(output).print();
}
